version: '3.1'
services:
    db:
        image: mysql
        container_name: derivery
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root  
            MYSQL_DATABASE: derivery     
        ports: 
            - "3307:3306"
        security_opt:
                - seccomp:unconfined
        volumes: 
            - microex:/var/lib/mysql

volumes: 
  microex: