# H@
spring:
    h2:
        console:   
            enabled: true
            path: /h2-console
    
    datasource:
        url: jdbc:h2:file:~/teste
        username: sa
        password: 
        driver-class-name: org.h2.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update



